---
apiVersion: v1
kind: Pod
metadata:
  name: podclient
  namespace: tenantblue
  annotations:
    k8s.v1.cni.cncf.io/networks: shared-net
spec:
  containers:
  - name: http-server
    image: k8s.gcr.io/e2e-test-images/agnhost:2.36
    args: [ "pause" ]
    securityContext:
      runAsUser: 1000
      privileged: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Pod
metadata:
  name: blue-server
  namespace: tenantblue
  annotations:
    k8s.v1.cni.cncf.io/networks: shared-net
spec:
  containers:
  - name: http-server
    image: k8s.gcr.io/e2e-test-images/agnhost:2.36
    args:
    - "netexec"
    - "--http-port"
    - "9000"
    ports:
    - name: webserver
      protocol: TCP
      containerPort: 9000
    securityContext:
      runAsUser: 1000
      privileged: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Pod
metadata:
  name: yellow-server
  namespace: tenantyellow
  annotations:
    k8s.v1.cni.cncf.io/networks: shared-net
spec:
  containers:
  - name: http-server
    image: k8s.gcr.io/e2e-test-images/agnhost:2.36
    args:
    - "netexec"
    - "--http-port"
    - "9000"
    ports:
    - name: webserver
      protocol: TCP
      containerPort: 9000
    securityContext:
      runAsUser: 1000
      privileged: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      allowPrivilegeEscalation: false

